### ISSUE TITLE
Hotkeys seem not work for Mac

### ISSUE THREAD

**Issue by happyj1116** [sashaweiss/vscode-bracket-jumper#6]
Hotkeys are not useful for the extension, they are useful for Mac control panel.
Thus I  don't know how to quickly switch paired bracket or next brackets.

**Comment by sashaweiss** [comment]
Hi! Sorry you're having an issue.

You should be able to override the default hotkeys, to make them something that doesn't conflict with control panel.

Alternatively, if you don't use control panel much I believe you can also configure that to use different hotkeys, and then the defaults for Bracket Jumper will work.

**Comment by sashaweiss** [comment]
Just tried it myself, and I see what you mean - that's frustrating. When I wrote this originally it didn't conflict - I bet the Mac shortcut has updated since then. (Or maybe I had that shortcut disabled at the time...I'm no longer on the machine I originally wrote this on, so can't verify that unfortunately.)

I'm worried that pushing an update that changes the default keybindings (to avoid the conflict with Control Panel) will break the workflows of existing users. So for the moment, I recommend working around this by overriding the configuration.

Sorry you ran into this!

**Comment by hyj1116** [comment]
It works after I overrode the configuration!

Thanks for the awesome extension! 👍

**Comment by sashaweiss** [comment]
Haha I'm so glad you're finding it useful!!
